version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=carsharingdb
    networks:
      - mynetwork

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=carsharingdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

networks:
  mynetwork:

volumes:
  db_data: